import {px,line,ellipse,diamond,circle,ring,shard,tendril,orbit,core} from './visual-primitives.js';
function satellites(ctx,cx,cy,count,spread,stage,p,black,rng,s,tail=false){for(let i=0;i<count;i++){const a=i/count*Math.PI*2+r=spread+rng()*2,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;circle(ctx,x,y,1,s,p.mid,.9);core(ctx,x,y,s,p.glow,black);if(tail)tendril(ctx,x,y+1,2+stage,Math.PI/2,.5+i,s,p.mid,.55)}}
export function drawFamily(ctx,family,o){const {cx,cy,s,stage,variant,p,black,rng,frag,tend,crystal,shell,frame}=o;switch(family){
case'eclipse_wraith':{const hy=cy-6-stage,bh=8+stage*2+(variant===2?2:0);ellipse(ctx,cx,hy,3,3,s,p.mid,.95);for(let y=0;y<bh;y++){const sp=Math.max(1,Math.round(y/bh*(4.5+stage)));for(let x=-sp;x<=sp;x++)px(ctx,cx+x,hy+2+y,s,y<bh*.45?p.body:p.mid,.9)}for(let i=0;i<3+Math.floor(tend/25);i++)tendril(ctx,cx-2+i*2,hy+bh,4+stage,Math.PI/2,.6+i,s,p.mid,.78);if(stage>=1)ring(ctx,cx,hy-1,4+Math.floor(shell/42),s,p.pale,.66);core(ctx,cx,hy,s,p.glow,black);break}
case'drip_maw':{const t=cy-7-stage,b=cy+7+stage;line(ctx,cx-4,t,cx-1,cy,s,p.mid,.92);line(ctx,cx+4,t,cx+1,cy,s,p.mid,.92);line(ctx,cx-1,cy,cx-4,b,s,p.mid,.92);line(ctx,cx+1,cy,cx+4,b,s,p.mid,.92);for(let y=-4-stage;y<=4+stage;y++){const sp=2+Math.floor((1-Math.abs(y)/(5+stage))*2.2);for(let x=-sp;x<=sp;x++)px(ctx,cx+x,cy+y,s,Math.abs(x)<1?p.body:p.mid,.92)}for(let i=0;i<3+stage;i++){px(ctx,cx-2+i,cy-(4+stage)+i,s,p.pale,.88);px(ctx,cx-2+i,cy+(4+stage)-i,s,p.pale,.88)}core(ctx,cx,cy,s,p.glow,black);break}
case'crystal_bulwark':{diamond(ctx,cx,cy,4+stage,5+stage,s,p.body,.95);diamond(ctx,cx,cy,2+stage*.4,4+stage,s,p.mid,.92);const n=4+Math.floor(crystal/22)+variant;for(let i=0;i<n;i++){const a=i/n*Math.PI*2,d=7+stage+rng()*3;shard(ctx,cx+Math.cos(a)*d,cy+Math.sin(a)*d,2+stage*.7,a,s,p.pale,.84)}core(ctx,cx,cy,s,p.glow,black);break}
case'split_obelisk':{line(ctx,cx,cy-6-stage,cx,cy+6+stage,s,p.mid,.85);diamond(ctx,cx-2,cy,2+stage,4+stage,s,p.body,.92);diamond(ctx,cx+2,cy-1,2+stage,5+stage,s,p.body,.92);shard(ctx,cx-5-stage,cy-2,3+stage*.5,Math.PI,s,p.pale,.86);shard(ctx,cx+5+stage,cy+1,3+stage*.5,0,s,p.pale,.86);core(ctx,cx,cy-1,s,p.glow,black);break}
case'orbital_eye':{circle(ctx,cx,cy,4+stage,s,p.body,.95);core(ctx,cx,cy,s,p.glow,black);ring(ctx,cx,cy-1,6+stage+(variant===2?1:0),s,p.pale,.74);orbit(ctx,cx,cy-1,7+stage,4+stage+(variant===1?2:0),frame/20,s,p.glow,.76);break}
case'halo_shrine':{line(ctx,cx,cy-7-stage,cx,cy+7+stage,s,p.mid,.84);diamond(ctx,cx,cy+2,3+stage,5+stage,s,p.body,.95);ring(ctx,cx,cy-8-stage,4+(variant===1?1:0),s,p.pale,.7);satellites(ctx,cx,cy,3+stage+variant,8+stage,stage,p,black,rng,s,true);core(ctx,cx,cy+2,s,p.glow,black);core(ctx,cx,cy-8-stage,s,p.glow,black);break}
case'jelly_halo':{ellipse(ctx,cx,cy-2,4+stage,5+stage,s,p.body,.94);for(let i=0;i<4+stage+variant;i++)tendril(ctx,cx-3+i*1.6,cy+2,4+stage,Math.PI/2,.4+i,s,p.mid,.74);ring(ctx,cx,cy-5,6+stage,s,p.pale,.68);orbit(ctx,cx,cy-5,6+stage,4+stage,frame/18,s,p.glow,.74);core(ctx,cx,cy-2,s,p.glow,black);break}
case'hourglass_dual':{circle(ctx,cx,cy-5-stage,3+stage,s,p.body,.92);circle(ctx,cx,cy+5+stage,3+stage,s,p.body,.92);line(ctx,cx-1,cy-2,cx+1,cy+2,s,p.mid,.84);line(ctx,cx+1,cy-2,cx-1,cy+2,s,p.mid,.84);orbit(ctx,cx,cy-5-stage,5,4,frame/25,s,p.pale,.72);orbit(ctx,cx,cy+5+stage,5,4,-frame/25,s,p.pale,.72);core(ctx,cx,cy-5-stage,s,p.glow,black);core(ctx,cx,cy+5+stage,s,p.glow,black);break}
case'colony_bloom':{circle(ctx,cx,cy,3+stage,s,p.body,.9);core(ctx,cx,cy,s,p.glow,black);const n=6+stage+Math.floor(frag/22)+variant;for(let i=0;i<n;i++){const a=i/n*Math.PI*2+rng()*.35,d=5+stage*1.6+rng()*4,x=cx+Math.cos(a)*d,y=cy+Math.sin(a)*d;circle(ctx,x,y,1+(i%4===0),s,p.mid,.92);core(ctx,x,y,s,p.glow,black);if(rng()>.35)line(ctx,cx,cy,x,y,s,p.mid,.18)}break}
case'serpent_maw':{for(let i=0;i<8+stage*2;i++)px(ctx,cx+Math.sin(i*.55)*2.2,cy-6+i,s,p.body,.93);ellipse(ctx,cx+2,cy-6,3,3,s,p.mid,.95);for(let i=0;i<4;i++){px(ctx,cx+4+i*.5,cy-6+i*.5,s,p.pale,.86);px(ctx,cx+1-i*.5,cy-6+i*.5,s,p.pale,.86)}core(ctx,cx+2,cy-6,s,p.glow,black);break}
case'tendril_tree':{line(ctx,cx,cy-6-stage,cx,cy+6+stage,s,p.mid,.84);circle(ctx,cx,cy-5-stage,2+Math.floor(stage/2),s,p.body,.95);core(ctx,cx,cy-4-stage,s,p.glow,black);const n=5+Math.floor(tend/18)+stage+variant;for(let i=0;i<n;i++){const a=i/n*Math.PI*2,d=(Math.sin(a)>0?Math.PI/2:-Math.PI/2)+Math.cos(a)*.7;tendril(ctx,cx,cy-1+Math.sin(a)*2,4+stage,d,a+i,s,p.mid,.8)}break}
case'phase_lance':{diamond(ctx,cx,cy,3+stage,7+stage*2,s,p.mid,.96);shard(ctx,cx,cy-8-stage,4+stage*.7,-Math.PI/2,s,p.pale,.88);shard(ctx,cx-5-stage,cy+1,3+stage*.5,Math.PI,s,p.pale,.78);shard(ctx,cx+5+stage,cy-1,3+stage*.5,0,s,p.pale,.78);core(ctx,cx,cy,s,p.glow,black);break}
case'void_reliquary':{diamond(ctx,cx,cy,5+stage,7+stage*2,s,p.body,.94);diamond(ctx,cx,cy,3+stage,5+stage,s,'#06070b',.98);ring(ctx,cx,cy,5+stage,s,p.pale,.48);satellites(ctx,cx,cy,4+stage+variant,9+stage,stage,p,black,rng,s,false);core(ctx,cx,cy,s,p.glow,black);break}
case'procession_tower':default:{line(ctx,cx,cy-7-stage,cx,cy+8+stage,s,p.mid,.86);ellipse(ctx,cx,cy-8-stage,3,2,s,p.mid,.95);diamond(ctx,cx,cy+1,4+stage,6+stage,s,p.body,.94);for(let i=0;i<3+stage;i++)core(ctx,cx+(i%2?1:-1),cy-3+i*3,s,p.glow,black);satellites(ctx,cx,cy,2+stage+variant,9+stage,stage,p,black,rng,s,true);ring(ctx,cx,cy-9-stage,4,s,p.pale,.62);break}}}
